DATASET_PATHS = [
    "datasets/COVID-19_Radiography.zip",
    "datasets/VinXRay.zip"
]

# TRAINING SETTINGS
NUM_EPOCHS = 3

# LEARNING RATE SETTINGS
BASE_LR = 0.0001
DECAY_WEIGHT = 0.1 
EPOCH_DECAY = 30 

# DATASET INFO
NUM_CLASSES = 2

# DATALOADER PROPERTIES
BATCH_SIZE = 64
NUM_WORKERS = 8
